---
- name: Deploy Flask App
  hosts: g1
  become: yes

  tasks:
    - name: Add the default Ubuntu repository
      apt_repository:
        repo: 'deb http://archive.ubuntu.com/ubuntu focal main'
        state: present

    - name: Install required packages
      package:
        name:
          - python3
          - python3-pip
          - git

    - name: Create the destination folder
      file:
        path: /opt/flaskApp2
        state: directory

    - name: Clone the repository
      git:
        repo: https://github.com/BasedOnBelieve/devops2.git
        dest: /opt/flaskApp2
     
    - name: Install Flask and its dependencies
      pip:
        name: flask
        virtualenv: /opt/flask-env
        chdir: /opt/flaskApp2p

    - name: Start the Flask App
      command: /opt/flask-env/bin/python3 /opt/flaskApp2/app.py
      async: 1
      poll: 0
